name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.4
    - uses: actions/setup-node@v2-beta
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Install dependencies
      run: "bundle install --without development"
    - name: Setup Node
      uses: actions/setup-node@v1
    - run: "yarn check || bin/rails yarn:install"
    - name: Run test
      run: "bin/rails test"
